### ISSUE TITLE
faq.html and contact.html contain raintpl variables

### ISSUE THREAD

**Issue by exec** [Zayotic/Plutobin#1]
It appears the files /faq.html and /contact.html contain internal variables that are executed by the RainTPL engine, and would therefore render the html invalid since it's unprocessed by the engine. A workaround would be to either include the files as "/contact.php" and "/faq.php" and include them in the RainTPL engine execution (which would be unnecessary as neither file is included in the ZeroBin engine) or replace the variables with static values.

Another viable option would be to include any relevant contact information in either the footer of the primary paste page or as a JS modal that's opened on a button click, etc. That would save space and time.

Examples:

```
<link type="text/css" rel="stylesheet" href="css/plutobin.css?{$VERSION|rawurlencode}#" /> 
<link type="text/css" rel="stylesheet" href="css/paste.css?{$VERSION|rawurlencode}#" />
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<script src="js/jquery.js?{$VERSION|rawurlencode}#"></script>
<script src="js/sjcl.js?{$VERSION|rawurlencode}#"></script>
<script src="js/base64.js?{$VERSION|rawurlencode}#"></script>
<script src="js/rawdeflate.js?{$VERSION|rawurlencode}#"></script>
<script src="js/rawinflate.js?{$VERSION|rawurlencode}#"></script>
<script src="js/zerobin.js?{$VERSION|rawurlencode}#"></script>
<script src="js/bootstap.js?{$VERSION|rawurlencode}#"></script>
<link type="text/css" rel="stylesheet" href="js/highlight.styles/monokai.css?{$VERSION|rawurlencode}#">
<script src="js/highlight.pack.js?{$VERSION|rawurlencode}#"></script>
```

**Comment by Zayotic** [comment]
All issues have been fixed. Thanks for the issue.
